version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    ports:
      - "8080:8080"
    container_name: keycloak
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak-network

  keycloak_postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    container_name: keycloak_postgres
    networks:
      - keycloak-network
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

networks:
  keycloak-network:

volumes:
  keycloak_db_data:
