version: '3.8'

services:
  keycloak_postgres:
    image: postgres:16
    container_name: keycloak_postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    networks:
      - keycloak-network
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Ensure schema creation
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak_a:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_a
    restart: always
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=secure_password
      - KC_DB_SCHEMA=keycloak_a  # Isolate schema for keycloak_a
      - KC_DB_SCHEMA_UPDATE=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak_b:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_b
    restart: always
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=secure_password
      - KC_DB_SCHEMA=keycloak_b  # Isolate schema for keycloak_b
      - KC_DB_SCHEMA_UPDATE=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KEYCLOAK_ADMIN=admin2
      - KEYCLOAK_ADMIN_PASSWORD=admin2
    command: ["start-dev"]
    ports:
      - "8082:8080"
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak_db_data: